/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import com.bulenkov.darcula.DarculaLaf;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.basic.BasicLookAndFeel;

/**
 *
 * @author djani
 */
public class MainFrame extends javax.swing.JFrame {
    
    public static final int SZELESSEG = 600;
    public static final int MAGASSAG = 400;
    public static final String CIM = "Mobilfónia";

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        this.setSize(SZELESSEG, MAGASSAG);
        this.setTitle(CIM);
        this.setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mobilJPanel1 = new feluletek.MobilJPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fajlMenu = new javax.swing.JMenu();
        beolvasasMenuPont = new javax.swing.JMenuItem();
        kilepesMenuPont = new javax.swing.JMenuItem();
        rendezesMenu = new javax.swing.JMenu();
        novekvojRadioButton = new javax.swing.JRadioButtonMenuItem();
        csokkenojRadioButton = new javax.swing.JRadioButtonMenuItem();
        sugoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fajlMenu.setText("Fájl");

        beolvasasMenuPont.setText("Adatbevitel Fájlból");
        beolvasasMenuPont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beolvasasMenuPontActionPerformed(evt);
            }
        });
        fajlMenu.add(beolvasasMenuPont);

        kilepesMenuPont.setText("Kilépés");
        kilepesMenuPont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilepesMenuPontActionPerformed(evt);
            }
        });
        fajlMenu.add(kilepesMenuPont);

        jMenuBar1.add(fajlMenu);

        rendezesMenu.setText("Rendezés");

        buttonGroup1.add(novekvojRadioButton);
        novekvojRadioButton.setText("Növekvő");
        rendezesMenu.add(novekvojRadioButton);

        buttonGroup1.add(csokkenojRadioButton);
        csokkenojRadioButton.setSelected(true);
        csokkenojRadioButton.setText("Csökkenő");
        rendezesMenu.add(csokkenojRadioButton);

        jMenuBar1.add(rendezesMenu);

        sugoMenu.setText("Névjegy");
        sugoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sugoMenuMousePressed(evt);
            }
        });
        jMenuBar1.add(sugoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mobilJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mobilJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kilepesMenuPontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilepesMenuPontActionPerformed
        System.exit(0);
    }//GEN-LAST:event_kilepesMenuPontActionPerformed

    private void beolvasasMenuPontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beolvasasMenuPontActionPerformed
        mobilJPanel1.fixFajlbol();
    }//GEN-LAST:event_beolvasasMenuPontActionPerformed

    private void sugoMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sugoMenuMousePressed
        JOptionPane.showMessageDialog(null, "Dobszai János\nI5D2TG", "Súgó", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_sugoMenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /*  ___ DARCULA TÉMA BEÁLLÍTÁSA ___  */
        
        BasicLookAndFeel laf = new DarculaLaf();
        try {
            UIManager.setLookAndFeel(laf);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /* Set the Nimbus look and feel --- ___ KIKOMMENTELVE! ___ */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
                
        for (javax.swing.UIManager.LookAndFeelInfo stuff : javax.swing.UIManager.getInstalledLookAndFeels()){
            System.out.println(stuff.getName());
        }
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem beolvasasMenuPont;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButtonMenuItem csokkenojRadioButton;
    private javax.swing.JMenu fajlMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem kilepesMenuPont;
    private feluletek.MobilJPanel mobilJPanel1;
    private javax.swing.JRadioButtonMenuItem novekvojRadioButton;
    private javax.swing.JMenu rendezesMenu;
    private javax.swing.JMenu sugoMenu;
    // End of variables declaration//GEN-END:variables
}
